-- Lao Web Studio V3.0 Stable — Complete Supabase Setup
create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text default '', email text, role text not null default 'customer',
 is_active boolean not null default true, created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.leads(
 id bigint generated by default as identity primary key,
 name text not null, phone text not null, email text, business_name text,
 service text default 'website', budget text, message text not null,
 preferred_contact text default 'whatsapp', language text default 'lo',
 status text default 'new', source text default 'website',
 created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.appointments(
 id uuid primary key default gen_random_uuid(), title text not null,
 appointment_at timestamptz not null, lead_id bigint references public.leads(id) on delete set null,
 status text default 'scheduled', note text, created_at timestamptz default now()
);

create table if not exists public.quotations(
 id uuid primary key default gen_random_uuid(), quote_no text unique not null,
 lead_id bigint references public.leads(id) on delete set null, customer_name text not null,
 amount numeric(14,2) default 0, currency text default 'ກີບ', status text default 'draft',
 created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.tasks(
 id uuid primary key default gen_random_uuid(), title text not null, description text,
 customer_user_id uuid references auth.users(id) on delete set null,
 status text default 'todo', priority text default 'medium', progress int default 0,
 due_date date, created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.invoices(
 id uuid primary key default gen_random_uuid(), invoice_number text unique not null,
 customer_user_id uuid references auth.users(id) on delete set null,
 customer_name text not null, total numeric(14,2) default 0, currency text default 'ກີບ',
 status text default 'draft', due_date date, created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.payments(
 id uuid primary key default gen_random_uuid(), invoice_id uuid references public.invoices(id) on delete cascade,
 amount numeric(14,2) not null, payment_date date default current_date, created_at timestamptz default now()
);

create table if not exists public.project_updates(
 id uuid primary key default gen_random_uuid(), customer_user_id uuid references auth.users(id) on delete cascade,
 title text not null, message text, progress int default 0, status text default 'in_progress',
 is_visible_to_customer boolean default true, created_at timestamptz default now()
);

create table if not exists public.employees(
 id uuid primary key default gen_random_uuid(), name text not null, email text,
 role text default 'staff', active boolean default true, created_at timestamptz default now()
);

create or replace function public.lws_current_role() returns text language sql stable security definer set search_path=public as $$
 select coalesce((select role from public.profiles where id=auth.uid() and is_active=true),'customer');
$$;
create or replace function public.lws_is_staff() returns boolean language sql stable security definer set search_path=public as $$
 select public.lws_current_role() in ('owner','manager','staff');
$$;

drop function if exists public.submit_public_lead(text,text,text,text,text,text,text,text,text);
create function public.submit_public_lead(
 p_name text,p_phone text,p_email text default null,p_business_name text default null,
 p_service text default 'website',p_budget text default null,p_message text default '',
 p_preferred_contact text default 'whatsapp',p_language text default 'lo'
) returns text language plpgsql security definer set search_path=public as $$
declare v_id text;
begin
 if nullif(btrim(p_name),'') is null then raise exception 'name_required'; end if;
 if nullif(btrim(p_phone),'') is null then raise exception 'phone_required'; end if;
 if nullif(btrim(p_message),'') is null then raise exception 'message_required'; end if;
 insert into public.leads(name,phone,email,business_name,service,budget,message,preferred_contact,language,status,source)
 values(btrim(p_name),btrim(p_phone),nullif(btrim(coalesce(p_email,'')),''),
 nullif(btrim(coalesce(p_business_name,'')),''),
 coalesce(nullif(btrim(p_service),''),'website'),
 nullif(btrim(coalesce(p_budget,'')),''),
 btrim(p_message),coalesce(nullif(btrim(p_preferred_contact),''),'whatsapp'),
 case when p_language in ('lo','th','en') then p_language else 'lo' end,'new','website')
 returning id::text into v_id;
 return v_id;
end $$;
grant execute on function public.submit_public_lead(text,text,text,text,text,text,text,text,text) to anon,authenticated;

create or replace function public.lws_health_check() returns jsonb language sql stable security definer set search_path=public as $$
 select jsonb_build_object('ok',true,'version','3.0.0','lead_rpc',true,'checked_at',now());
$$;
grant execute on function public.lws_health_check() to anon,authenticated;

create or replace function public.lws_handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name,email,role)
 values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email,
 case when not exists(select 1 from public.profiles where role='owner') then 'owner' else 'customer' end)
 on conflict(id) do update set email=excluded.email,updated_at=now();
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.lws_handle_new_user();

do $$
declare t text; p record;
begin
 foreach t in array array['profiles','leads','appointments','quotations','tasks','invoices','payments','project_updates','employees']
 loop
  execute format('alter table public.%I enable row level security',t);
  for p in select policyname from pg_policies where schemaname='public' and tablename=t
  loop execute format('drop policy if exists %I on public.%I',p.policyname,t); end loop;
 end loop;
end $$;

create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.lws_is_staff());
create policy profiles_manage on public.profiles for all to authenticated using(public.lws_current_role() in ('owner','manager')) with check(public.lws_current_role() in ('owner','manager'));
create policy leads_staff on public.leads for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy appointments_staff on public.appointments for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy quotations_staff on public.quotations for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy tasks_read on public.tasks for select to authenticated using(public.lws_is_staff() or customer_user_id=auth.uid());
create policy tasks_write on public.tasks for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy invoices_read on public.invoices for select to authenticated using(public.lws_is_staff() or customer_user_id=auth.uid());
create policy invoices_write on public.invoices for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy payments_read on public.payments for select to authenticated using(public.lws_is_staff() or exists(select 1 from public.invoices i where i.id=payments.invoice_id and i.customer_user_id=auth.uid()));
create policy payments_write on public.payments for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy updates_read on public.project_updates for select to authenticated using(public.lws_is_staff() or (customer_user_id=auth.uid() and is_visible_to_customer=true));
create policy updates_write on public.project_updates for all to authenticated using(public.lws_is_staff()) with check(public.lws_is_staff());
create policy employees_staff on public.employees for all to authenticated using(public.lws_is_staff()) with check(public.lws_current_role() in ('owner','manager'));

notify pgrst,'reload schema';
select jsonb_build_object('result','installed','version','3.0.0','rpc_ready',to_regprocedure('public.submit_public_lead(text,text,text,text,text,text,text,text,text)') is not null,'tables_ready',(select count(*) from information_schema.tables where table_schema='public' and table_name in ('profiles','leads','appointments','quotations','tasks','invoices','payments','project_updates','employees'))) as installation_result;
